import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/Footer";
const roboto = Roboto({ subsets: ["latin"],weight:"400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme='dark' lang="en">
      <body className={roboto.className}>
       < main className=" max-w-4xl mx-auto px-3 py-3">
        <Header />
        {children}
        <Footer />
       </main>
    
        </body>
    </html>
  );
}
